module.exports = (film, base64) => {
    return {
        id: film.id,
        title: film.title,
        review: film.review,
        photo: base64,
        rating: film.rating,
        views: film.views,
        year: film.year,
        city: film.city,
        genre: film.genre,
        slogan: film.slogan,
        director: film.director,
        scenario: film.scenario,
        producer: film.producer,
        operator: film.operator,
        composer: film.composer,
        painter: film.painter,
        mounting: film.mounting,
        budget: film.budget,
        feesus: film.feesus,
        feesworld: film.feesworld,
        watchers: film.watchers,
        premiererf: film.premiererf,
        premiereworld: film.premiereworld,
        releaserf: film.releaserf,
        releasedvd: film.releasedvd,
        estimate: film.estimate,
        age: film.age,
        reitingmpaa: film.reitingmpaa,
        time: film.time,
        id_user: film.id_user,
        createdAt: film.createdAt,
    };
};
