'use strict';

module.exports = {
    up: async (queryInterface, Sequelize) => {
        return queryInterface.bulkInsert('kinos', [
            {
                title: 'Аладдин',
                review:
                    'Волшебная сказка от Гая Ричи, вдохновленная знаменитым мультфильмом Disney',
                photo: 'aladin.jpeg',
                rating: '8.7',
                views: '332921',
                year: '2019',
                city: 'США, Великобритания, Австралия',
                genre: 'мюзикл, фэнтези, мелодрама, приключения, семейный',
                slogan: '-',
                director: 'Гай Ричи',
                scenario: 'Джон Огаст, Гай Ричи',
                producer:
                    'Айван Эткинсон, Кевин Де Ла Ной, Джонатан Эйрих, ...',
                operator: 'Алан Стюарт',
                composer: 'Алан Менкен',
                painter: 'Джемма Джексон, Рави Бансал, Оливер Кэрролл, ...',
                mounting: 'Джеймс Херберт',
                budget: '$183 000 000',
                feesus: '$355 559 216',
                feesworld: '+ $695 134 737 = $1 050 693 953',
                watchers: '$21 825 132',
                premiererf: '23 мая 2019, «WDSSPR»',
                premiereworld: '8 мая 2019, ...',
                releaserf: '14124',
                releasedvd: '30 августа 2019, «Уолт Дисней Компани СНГ»',
                age: '6+',
                reitingmpaa: 'PG',
                time: '128 мин. / 02:08',
                usersKinoId: 3,
                estimate: 0.0,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: 'Джентльмены',
                review:
                    'Успешное возвращение Гая Ричи к корням — острая и живая криминальная комедия с блестящим актерским составом',
                photo: 'jent.jpeg',
                rating: '9.1',
                views: '475621',
                year: '2019',
                city: 'США',
                genre: 'Великобритания, США',
                slogan: 'криминал, комедия, боевик',
                director: '«Criminal. Class»',
                scenario: 'Гай Ричи',
                producer: 'Гай Ричи, Айван Эткинсон, Марн Дэвис, ...',
                operator: 'Мэттью Андерсон, Айван Эткинсон, Билл Блок, ...',
                composer: 'Алан Стюарт',
                painter: 'Кристофер Бенстед',
                mounting: 'Джемма Джексон, Рэйчел Олтон, Оливер Кэрролл, ...',
                budget: 'Джеймс Херберт, Пол Мачлисс',
                feesus: '$22 000 000',
                feesworld: '$36 471 795',
                watchers: '+ $78 700 000 = $115 171 795',
                premiererf: '$18 003 343',
                premiereworld: '13 февраля 2020, «Вольга»',
                releaserf: '3 декабря 2019, ...',
                releasedvd: '31 марта 2020, «Вольга»',
                age: '18+',
                reitingmpaa: 'R',
                time: '113 мин. / 01:53',
                usersKinoId: 3,
                estimate: 0.0,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: 'Карты, деньги, два ствола',
                review:
                    'Дебют Гая Ричи — стильная комедия про ограбление с участием Винни Джонса и Джейсона Стэйтема',
                photo: 'kurt.jpg',
                rating: '6.9',
                views: '287232',
                year: '1998',
                city: 'Великобритания',
                genre: 'боевик, комедия, криминал',
                slogan:
                    '«They lost half a million at cards but theyve still got a few tricks up their sleeve»',
                director: 'Гай Ричи',
                scenario: 'Гай Ричи',
                producer: 'Мэттью Вон, Стефен Маркс, Джорджия Мастерс, ...',
                operator: 'Тим Морис-Джонс',
                composer: 'Дэвид А. Хьюз, Джон Мерфи',
                painter: 'Иэн Эндрюс, Ив Мавракис, Стефани Колли, ...',
                mounting: 'Найвен Хоуи',
                budget: '£ 960 000',
                feesus: '$3 753 929',
                feesworld: '$3 753 929',
                watchers:
                    'Великобритания2.9 млн, США767.2 тыс, Швеция155.2 тыс, ...',
                premiererf: '6 мая 1999, «Парадиз»',
                premiereworld: '23 августа 1998, ...',
                releaserf: '25 июля 2013, «Другое кино»',
                releasedvd: '1 сентября 1999, «Твистер»',
                age: '18+',
                reitingmpaa: 'R',
                time: '107 мин. / 01:47',
                usersKinoId: 4,
                estimate: 0.0,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: 'Агенты А.Н.К.Л.',
                review:
                    'Разведчик КГБ и бывший аферист из ЦРУ мешают нацистам собрать атомную бомбу. Авантюрный ретро-экшен Гая Ричи',
                photo: 'ankl.jpg',
                rating: '9.4',
                views: '525021',
                year: '2015',
                city: 'США, Великобритания',
                genre: 'боевик, комедия, приключения',
                slogan: '«Герои высшего класса»',
                director: 'Гай Ричи',
                scenario: 'Гай Ричи, Лайонел Уигрэм, Сэм Рольф, ...',
                producer: 'Стив Кларк-Холл, Джон Дэвис, Гай Ричи, ...',
                operator: 'Джон Мэтисон',
                composer: 'Дэниэл Пембертон',
                painter: 'Оливер Шолль, Дэвид Оллдей, Гай Брэдли, ...',
                mounting: 'Джеймс Херберт',
                budget: '$75 000 000',
                feesus: '$45 445 109',
                feesworld: '+ $61 600 000 = $107 045 109',
                watchers: '$9 351 636',
                premiererf: '13 августа 2015, «Каро-Премьер»',
                premiereworld: '2 августа 2015, ...',
                releaserf: '17 декабря 2015, «CP Дистрибуция»',
                releasedvd: '17 декабря 2015, «CP Дистрибуция»',
                age: '12+',
                reitingmpaa: 'PG-13',
                time: '116 мин. / 01:56',
                usersKinoId: 4,
                estimate: 0.0,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
        ]);
    },

    down: async (queryInterface, Sequelize) => {
        return queryInterface.bulkDelete('kinos', null, {});
    },
};
