module.exports = (fio, film, tmp) => {
    return {
        fio: fio,
        film: {
            id: film.id,
            title: film.title,
            review: film.review,
            photo: tmp,
            rating: film.rating,
            views: film.views,
            year: film.year,
            city: film.city,
            genre: film.genre,
            slogan: film.slogan,
            director: film.director,
            scenario: film.scenario,
            producer: film.producer,
            operator: film.operator,
            composer: film.composer,
            painter: film.painter,
            mounting: film.mounting,
            budget: film.budget,
            feesus: film.feesus,
            feesworld: film.feesworld,
            watchers: film.watchers,
            premiererf: film.premiererf,
            premiereworld: film.premiereworld,
            releaserf: film.releaserf,
            releasedvd: film.releasedvd,
            age: film.age,
            estimate: film.estimate,
            reitingmpaa: film.reitingmpaa,
            time: film.time,
        },
    };
};
