module.exports = dataAboutFilm => {
    return {
        title: dataAboutFilm.title,
        review: dataAboutFilm.review,
        photo: dataAboutFilm.photo,
        rating: dataAboutFilm.rating,
        views: dataAboutFilm.views,
        year: dataAboutFilm.year,
        city: dataAboutFilm.city,
        genre: dataAboutFilm.genre,
        slogan: dataAboutFilm.slogan,
        director: dataAboutFilm.director,
        scenario: dataAboutFilm.scenario,
        producer: dataAboutFilm.producer,
        operator: dataAboutFilm.operator,
        composer: dataAboutFilm.composer,
        painter: dataAboutFilm.painter,
        mounting: dataAboutFilm.mounting,
        budget: dataAboutFilm.budget,
        feesus: dataAboutFilm.feesus,
        feesworld: dataAboutFilm.feesworld,
        watchers: dataAboutFilm.watchers,
        premiererf: dataAboutFilm.premiererf,
        premiereworld: dataAboutFilm.premiereworld,
        releaserf: dataAboutFilm.releaserf,
        releasedvd: dataAboutFilm.releasedvd,
        age: dataAboutFilm.age,
        reitingmpaa: dataAboutFilm.reitingmpaa,
        time: dataAboutFilm.time,
        usersKinoId: dataAboutFilm.usersKinoId,
        estimate: dataAboutFilm.estimate,
    };
};
